### ISSUE TITLE
Compile warning on OOM code during kernel compile

### ISSUE THREAD

**Issue by siegfrkn** [siegfrkn/csci5573-project#1]
Not critical and doesn't stop the build, but would be fairly easy to resolve.

  CC      arch/x86/kernel/acpi/sleep.o
  CC      arch/x86/events/intel/lbr.o
mm/oom_kill.c: In function ‘get_graceful_shutdown_path’:
mm/oom_kill.c:328:19: warning: ‘f’ is used uninitialized in this function [-Wuninitialized]
  328 |         int len = kernel_read(f, buf, MAX_BUFFER_SIZE - 1, &f->f_pos);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  AS      arch/x86/kernel/acpi/wakeup_64.o
  CC      kernel/cgroup/freezer.o

**Comment by Dyfox100** [comment]
Should be fixed in most recent version. This was actually causing an error, because the file wasn't open. I had moved something to the top of the file to be c90 compliant, but messed it up.
